
package com.fameden.webservice.registration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.fameden.webservice.contracts.registration.FamedenRegistrationRequest;
import com.fameden.webservice.contracts.registration.FamedenRegistrationResponse;
import com.fameden.webservice.contracts.registration.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "registrationService", targetNamespace = "http://registration.contracts.webservice.fameden.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegistrationService {


    /**
     * 
     * @param registrationRequest
     * @return
     *     returns com.fameden.webservice.contracts.registration.FamedenRegistrationResponse
     */
    @WebMethod
    @WebResult(name = "registrationResponse", targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://registration.contracts.webservice.fameden.com/", className = "com.fameden.webservice.contracts.registration.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://registration.contracts.webservice.fameden.com/", className = "com.fameden.webservice.contracts.registration.RegisterUserResponse")
    @Action(input = "http://registration.contracts.webservice.fameden.com/registrationService/registerUserRequest", output = "http://registration.contracts.webservice.fameden.com/registrationService/registerUserResponse")
    public FamedenRegistrationResponse registerUser(
        @WebParam(name = "registrationRequest", targetNamespace = "")
        FamedenRegistrationRequest registrationRequest);

}
