
package com.fameden.webservice.registration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "registrationService", targetNamespace = "http://registration.webservice.fameden.com/", wsdlLocation = "http://rav-pc:8080/FameDenWS/registrationService?wsdl")
public class RegistrationService_Service
    extends Service
{

    private final static URL REGISTRATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTRATIONSERVICE_EXCEPTION;
    private final static QName REGISTRATIONSERVICE_QNAME = new QName("http://registration.webservice.fameden.com/", "registrationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rav-pc:8080/FameDenWS/registrationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRATIONSERVICE_WSDL_LOCATION = url;
        REGISTRATIONSERVICE_EXCEPTION = e;
    }

    public RegistrationService_Service() {
        super(__getWsdlLocation(), REGISTRATIONSERVICE_QNAME);
    }

    public RegistrationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRATIONSERVICE_QNAME, features);
    }

    public RegistrationService_Service(URL wsdlLocation) {
        super(wsdlLocation, REGISTRATIONSERVICE_QNAME);
    }

    public RegistrationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRATIONSERVICE_QNAME, features);
    }

    public RegistrationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegistrationService
     */
    @WebEndpoint(name = "RegistrationPort")
    public RegistrationService getRegistrationPort() {
        return super.getPort(new QName("http://registration.webservice.fameden.com/", "RegistrationPort"), RegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrationService
     */
    @WebEndpoint(name = "RegistrationPort")
    public RegistrationService getRegistrationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://registration.webservice.fameden.com/", "RegistrationPort"), RegistrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRATIONSERVICE_EXCEPTION!= null) {
            throw REGISTRATIONSERVICE_EXCEPTION;
        }
        return REGISTRATIONSERVICE_WSDL_LOCATION;
    }

}
